[package]
name = "store"
version = "0.1.0"
authors = ["Alberto Sonnino <alberto@sonnino.com>"]
edition = "2018"
publish = false

[dependencies]
rocksdb = "0.15.0"
tokio = { version = "0.3.1", features = ["sync", "macros", "rt"] }