[package]
name = "store"
version = "0.1.0"
authors = ["Alberto Sonnino <asonnino@fb.com>"]
edition = "2018"

[dependencies]
rocksdb = "0.15.0"
tokio = { version = "0.3.1", features = ["sync", "rt", "macros", "time"] }
futures = "0.3.8"