[package]
name = "node"
version = "0.1.0"
authors = ["Alberto Sonnino <alberto@sonnino.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0.21"
tokio = { version = "0.3.1", features = ["rt", "net", "time", "macros", "sync", "rt-multi-thread"] }
tokio-util = { version = "0.5", features= ["codec"] }
ed25519-dalek = { version = "1.0.1" }
log = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.61"
bytes = "0.6"
bincode = "1.3.1"
futures = "0.3.8"
rand = "0.7.3"
clap = "2.33.3"
env_logger = "0.8.2"

store = { path = "../store" }
crypto = { path = "../crypto" }
mempool = { path = "../mempool" }